// <auto-generated />
using System;
using EcoFive.Models.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EcoFive.Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210213184137_EditIDSuperAdminAndUser")]
    partial class EditIDSuperAdminAndUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EcoFive.Models.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<int>("CityId");

                    b.Property<bool>("CloseAccount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<int>("CountryId");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName");

                    b.Property<int>("GovernorateId");

                    b.Property<bool>("IsCaptain");

                    b.Property<bool>("IsSupplier");

                    b.Property<string>("LocationLatitude");

                    b.Property<string>("LocationLongitude");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("PhotoPath");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<string>("VisaDate");

                    b.Property<string>("VisaName");

                    b.Property<string>("VisaNumber");

                    b.Property<string>("VisaPassword");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "02174cf0–9412–4cfe-afbf-59f706d72cf6",
                            AccessFailedCount = 0,
                            CityId = 1,
                            CloseAccount = false,
                            ConcurrencyStamp = "bfa39272-5e40-41ce-9824-520d4bde0164",
                            CountryId = 1,
                            Email = "agmghazi@hotmail.com",
                            EmailConfirmed = true,
                            GovernorateId = 1,
                            IsCaptain = false,
                            IsSupplier = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "AGMGHAZI@HOTMAIL.COM",
                            NormalizedUserName = "AGMGHAZI",
                            PasswordHash = "AQAAAAEAACcQAAAAEBdziiZDeeqo2ppsUT9NTS03In2fDe+bgf2YQTsn7b1TmF1sLtBywbBHa7a9cRCoTQ==",
                            PhoneNumber = "0534740221",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "WN5B25J5JIF93FMHPKPOSUSVZ5BA3EFF",
                            TwoFactorEnabled = false,
                            UserName = "agmghazi"
                        },
                        new
                        {
                            Id = "02974cw0–9412–4nfe-afbf-59f701d72cf6",
                            AccessFailedCount = 0,
                            CityId = 1,
                            CloseAccount = false,
                            ConcurrencyStamp = "fc0a31ad-1b04-42b8-a3e6-1663b739f2f3",
                            CountryId = 1,
                            Email = "user1@hotmail.com",
                            EmailConfirmed = true,
                            GovernorateId = 1,
                            IsCaptain = false,
                            IsSupplier = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@HOTMAIL.COM",
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAEAACcQAAAAEGKbvHWhUakjXQ7j2K1UZUiFTdHP31MZTUy3cBB50w0xfrS7PFfkIEJPrZnBFwwlOA==",
                            PhoneNumber = "051265136845",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "WN5B25J5JIF93FMHPKPOSUSVZ5BA3EFF",
                            TwoFactorEnabled = false,
                            UserName = "user1"
                        });
                });

            modelBuilder.Entity("EcoFive.Models.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId");

                    b.Property<int>("GovernorateId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            GovernorateId = 1,
                            Name = "رأس تنورة"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            GovernorateId = 1,
                            Name = "الدمام"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            GovernorateId = 1,
                            Name = "النعيرية"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            GovernorateId = 1,
                            Name = "الخفجى"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            GovernorateId = 1,
                            Name = "حفر الباطن"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            GovernorateId = 1,
                            Name = "قرية العليا"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            GovernorateId = 1,
                            Name = "الخبر"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 1,
                            GovernorateId = 1,
                            Name = "القطيف"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 1,
                            GovernorateId = 1,
                            Name = "الاحساء"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 1,
                            GovernorateId = 1,
                            Name = "الجبيل"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 1,
                            GovernorateId = 1,
                            Name = "بقيق"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 1,
                            GovernorateId = 1,
                            Name = "العديد"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 1,
                            GovernorateId = 12,
                            Name = "غامد الزناد"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 1,
                            GovernorateId = 12,
                            Name = "المندق"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 1,
                            GovernorateId = 12,
                            Name = "المخواة"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 1,
                            GovernorateId = 12,
                            Name = "العقيق"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 1,
                            GovernorateId = 12,
                            Name = "قلوة"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 1,
                            GovernorateId = 12,
                            Name = "القرى"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 1,
                            GovernorateId = 12,
                            Name = "بني حسن"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 1,
                            GovernorateId = 12,
                            Name = "الحجرة"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 1,
                            GovernorateId = 12,
                            Name = "بلجرشي"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 1,
                            GovernorateId = 11,
                            Name = "سكاكا"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 1,
                            GovernorateId = 11,
                            Name = "القريات"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 1,
                            GovernorateId = 11,
                            Name = "دومة الجندل"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 1,
                            GovernorateId = 11,
                            Name = "طبرجل"
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 1,
                            GovernorateId = 10,
                            Name = "عرعر"
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 1,
                            GovernorateId = 10,
                            Name = "طريف"
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 1,
                            GovernorateId = 10,
                            Name = "رفحاء"
                        },
                        new
                        {
                            Id = 29,
                            CountryId = 1,
                            GovernorateId = 10,
                            Name = "العويقيلة"
                        },
                        new
                        {
                            Id = 30,
                            CountryId = 1,
                            GovernorateId = 10,
                            Name = "جديدة عرعر"
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 1,
                            GovernorateId = 10,
                            Name = "شعبة نصاب"
                        },
                        new
                        {
                            Id = 32,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "الدرعية"
                        },
                        new
                        {
                            Id = 33,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "الخرج"
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "الدوادمى"
                        },
                        new
                        {
                            Id = 36,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "المجمعة"
                        },
                        new
                        {
                            Id = 37,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "القويعية"
                        },
                        new
                        {
                            Id = 38,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "وادي الدواسر"
                        },
                        new
                        {
                            Id = 39,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "الأفلاج"
                        },
                        new
                        {
                            Id = 40,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "الزلفى"
                        },
                        new
                        {
                            Id = 41,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "شقراء"
                        },
                        new
                        {
                            Id = 42,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "حوطة بنى تميم"
                        },
                        new
                        {
                            Id = 43,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "عفيف"
                        },
                        new
                        {
                            Id = 44,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "السليل"
                        },
                        new
                        {
                            Id = 45,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "ضرما"
                        },
                        new
                        {
                            Id = 46,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "المزاحمية"
                        },
                        new
                        {
                            Id = 47,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "رماح"
                        },
                        new
                        {
                            Id = 48,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "ثادق"
                        },
                        new
                        {
                            Id = 49,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "حريملاء"
                        },
                        new
                        {
                            Id = 50,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "الحريق"
                        },
                        new
                        {
                            Id = 51,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "الغاط"
                        },
                        new
                        {
                            Id = 52,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "مرات"
                        },
                        new
                        {
                            Id = 53,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "الدلم"
                        },
                        new
                        {
                            Id = 54,
                            CountryId = 1,
                            GovernorateId = 7,
                            Name = "الرين"
                        },
                        new
                        {
                            Id = 55,
                            CountryId = 1,
                            GovernorateId = 8,
                            Name = "بريدة"
                        },
                        new
                        {
                            Id = 56,
                            CountryId = 1,
                            GovernorateId = 8,
                            Name = "عنيزة"
                        },
                        new
                        {
                            Id = 57,
                            CountryId = 1,
                            GovernorateId = 8,
                            Name = "الرس"
                        },
                        new
                        {
                            Id = 58,
                            CountryId = 1,
                            GovernorateId = 8,
                            Name = "المذنب"
                        },
                        new
                        {
                            Id = 59,
                            CountryId = 1,
                            GovernorateId = 8,
                            Name = "البكيرية"
                        },
                        new
                        {
                            Id = 60,
                            CountryId = 1,
                            GovernorateId = 8,
                            Name = "البدائع"
                        },
                        new
                        {
                            Id = 61,
                            CountryId = 1,
                            GovernorateId = 8,
                            Name = "الأسياح"
                        },
                        new
                        {
                            Id = 62,
                            CountryId = 1,
                            GovernorateId = 8,
                            Name = "النبهانية"
                        },
                        new
                        {
                            Id = 63,
                            CountryId = 1,
                            GovernorateId = 8,
                            Name = "عيون الجواء"
                        },
                        new
                        {
                            Id = 64,
                            CountryId = 1,
                            GovernorateId = 8,
                            Name = "الشماسية"
                        },
                        new
                        {
                            Id = 65,
                            CountryId = 1,
                            GovernorateId = 8,
                            Name = "عقلة الصقور"
                        },
                        new
                        {
                            Id = 66,
                            CountryId = 1,
                            GovernorateId = 8,
                            Name = "ضرية"
                        },
                        new
                        {
                            Id = 67,
                            CountryId = 1,
                            GovernorateId = 9,
                            Name = "ينبع"
                        },
                        new
                        {
                            Id = 68,
                            CountryId = 1,
                            GovernorateId = 9,
                            Name = "بدر"
                        },
                        new
                        {
                            Id = 69,
                            CountryId = 1,
                            GovernorateId = 9,
                            Name = "العلا"
                        },
                        new
                        {
                            Id = 70,
                            CountryId = 1,
                            GovernorateId = 9,
                            Name = "الحناكية"
                        },
                        new
                        {
                            Id = 71,
                            CountryId = 1,
                            GovernorateId = 9,
                            Name = "مهد الذهب"
                        },
                        new
                        {
                            Id = 72,
                            CountryId = 1,
                            GovernorateId = 9,
                            Name = "خيبر"
                        },
                        new
                        {
                            Id = 73,
                            CountryId = 1,
                            GovernorateId = 9,
                            Name = "العيص"
                        },
                        new
                        {
                            Id = 74,
                            CountryId = 1,
                            GovernorateId = 9,
                            Name = "وادي الفرع"
                        },
                        new
                        {
                            Id = 75,
                            CountryId = 1,
                            GovernorateId = 13,
                            Name = "تيماء"
                        },
                        new
                        {
                            Id = 76,
                            CountryId = 1,
                            GovernorateId = 13,
                            Name = "ضباء"
                        },
                        new
                        {
                            Id = 77,
                            CountryId = 1,
                            GovernorateId = 13,
                            Name = "الوجه"
                        },
                        new
                        {
                            Id = 78,
                            CountryId = 1,
                            GovernorateId = 13,
                            Name = "حقل"
                        },
                        new
                        {
                            Id = 79,
                            CountryId = 1,
                            GovernorateId = 13,
                            Name = "املج"
                        },
                        new
                        {
                            Id = 80,
                            CountryId = 1,
                            GovernorateId = 13,
                            Name = "البدع"
                        },
                        new
                        {
                            Id = 81,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "صبيا"
                        },
                        new
                        {
                            Id = 82,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "صامطة"
                        },
                        new
                        {
                            Id = 83,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "أبو عريش"
                        },
                        new
                        {
                            Id = 84,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "جازان"
                        },
                        new
                        {
                            Id = 85,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "أحد المسارحة"
                        },
                        new
                        {
                            Id = 86,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "بيش"
                        },
                        new
                        {
                            Id = 87,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "العارضة"
                        },
                        new
                        {
                            Id = 88,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "ضمد"
                        },
                        new
                        {
                            Id = 89,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "الدرب"
                        },
                        new
                        {
                            Id = 90,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "العيدابي"
                        },
                        new
                        {
                            Id = 91,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "الدائر"
                        },
                        new
                        {
                            Id = 92,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "الريث"
                        },
                        new
                        {
                            Id = 93,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "الحرث"
                        },
                        new
                        {
                            Id = 94,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "فرسان"
                        },
                        new
                        {
                            Id = 95,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "الطوال"
                        },
                        new
                        {
                            Id = 96,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "هروب"
                        },
                        new
                        {
                            Id = 97,
                            CountryId = 1,
                            GovernorateId = 6,
                            Name = "فيفاء"
                        },
                        new
                        {
                            Id = 98,
                            CountryId = 1,
                            GovernorateId = 5,
                            Name = "حائل"
                        },
                        new
                        {
                            Id = 99,
                            CountryId = 1,
                            GovernorateId = 5,
                            Name = "بقعاء"
                        },
                        new
                        {
                            Id = 100,
                            CountryId = 1,
                            GovernorateId = 5,
                            Name = "قفار"
                        },
                        new
                        {
                            Id = 101,
                            CountryId = 1,
                            GovernorateId = 5,
                            Name = "الغزالة"
                        },
                        new
                        {
                            Id = 102,
                            CountryId = 1,
                            GovernorateId = 5,
                            Name = "الشنان"
                        },
                        new
                        {
                            Id = 103,
                            CountryId = 1,
                            GovernorateId = 5,
                            Name = "موقق"
                        },
                        new
                        {
                            Id = 104,
                            CountryId = 1,
                            GovernorateId = 5,
                            Name = "الحائط"
                        },
                        new
                        {
                            Id = 105,
                            CountryId = 1,
                            GovernorateId = 5,
                            Name = "السليمي"
                        },
                        new
                        {
                            Id = 106,
                            CountryId = 1,
                            GovernorateId = 5,
                            Name = "الشملي"
                        },
                        new
                        {
                            Id = 107,
                            CountryId = 1,
                            GovernorateId = 5,
                            Name = "سميراء"
                        },
                        new
                        {
                            Id = 108,
                            CountryId = 1,
                            GovernorateId = 5,
                            Name = "الحليفة"
                        },
                        new
                        {
                            Id = 109,
                            CountryId = 1,
                            GovernorateId = 5,
                            Name = "تربه"
                        },
                        new
                        {
                            Id = 110,
                            CountryId = 1,
                            GovernorateId = 5,
                            Name = "جبة"
                        },
                        new
                        {
                            Id = 111,
                            CountryId = 1,
                            GovernorateId = 5,
                            Name = "وسيطاء الحفن"
                        },
                        new
                        {
                            Id = 112,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "أبها"
                        },
                        new
                        {
                            Id = 113,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "خميس مشيط"
                        },
                        new
                        {
                            Id = 114,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "بيشة"
                        },
                        new
                        {
                            Id = 115,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "النماص"
                        },
                        new
                        {
                            Id = 116,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "أحد رفيدة"
                        },
                        new
                        {
                            Id = 117,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "بارق"
                        },
                        new
                        {
                            Id = 118,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "البرك"
                        },
                        new
                        {
                            Id = 119,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "بلقرن"
                        },
                        new
                        {
                            Id = 120,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "تثليث"
                        },
                        new
                        {
                            Id = 121,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "تنومة"
                        },
                        new
                        {
                            Id = 122,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "رجال ألمع"
                        },
                        new
                        {
                            Id = 123,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "الحرجة"
                        },
                        new
                        {
                            Id = 124,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "سراة عبيدة"
                        },
                        new
                        {
                            Id = 125,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "طريب"
                        },
                        new
                        {
                            Id = 126,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "ظهران الجنوب"
                        },
                        new
                        {
                            Id = 127,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "محايل عسير"
                        },
                        new
                        {
                            Id = 128,
                            CountryId = 1,
                            GovernorateId = 4,
                            Name = "المجاردة"
                        },
                        new
                        {
                            Id = 129,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "مكه"
                        },
                        new
                        {
                            Id = 130,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "جدة"
                        },
                        new
                        {
                            Id = 131,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "الطائف"
                        },
                        new
                        {
                            Id = 132,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "رابغ"
                        },
                        new
                        {
                            Id = 133,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "الكامل"
                        },
                        new
                        {
                            Id = 134,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "القنفذة"
                        },
                        new
                        {
                            Id = 135,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "تربة"
                        },
                        new
                        {
                            Id = 136,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "الليث"
                        },
                        new
                        {
                            Id = 137,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "الجموم"
                        },
                        new
                        {
                            Id = 138,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "خليص"
                        },
                        new
                        {
                            Id = 139,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "أضم"
                        },
                        new
                        {
                            Id = 140,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "الخرمة"
                        },
                        new
                        {
                            Id = 141,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "رنية"
                        },
                        new
                        {
                            Id = 142,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "العرضيات"
                        },
                        new
                        {
                            Id = 143,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "الموية"
                        },
                        new
                        {
                            Id = 144,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "ميسان"
                        },
                        new
                        {
                            Id = 145,
                            CountryId = 1,
                            GovernorateId = 3,
                            Name = "بحرة"
                        },
                        new
                        {
                            Id = 146,
                            CountryId = 1,
                            GovernorateId = 2,
                            Name = "نجران"
                        },
                        new
                        {
                            Id = 147,
                            CountryId = 1,
                            GovernorateId = 2,
                            Name = "شرورة"
                        },
                        new
                        {
                            Id = 148,
                            CountryId = 1,
                            GovernorateId = 2,
                            Name = "الحصينية"
                        },
                        new
                        {
                            Id = 149,
                            CountryId = 1,
                            GovernorateId = 2,
                            Name = "ثار"
                        },
                        new
                        {
                            Id = 150,
                            CountryId = 1,
                            GovernorateId = 2,
                            Name = "يدمه"
                        },
                        new
                        {
                            Id = 151,
                            CountryId = 1,
                            GovernorateId = 2,
                            Name = "بدر الجنوب"
                        },
                        new
                        {
                            Id = 152,
                            CountryId = 1,
                            GovernorateId = 2,
                            Name = "خباش"
                        },
                        new
                        {
                            Id = 153,
                            CountryId = 1,
                            GovernorateId = 2,
                            Name = "الخرخير"
                        });
                });

            modelBuilder.Entity("EcoFive.Models.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Email");

                    b.Property<string>("Message");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("EcoFive.Models.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "المملكه العربية السعودية"
                        },
                        new
                        {
                            Id = 2,
                            Name = "مصر"
                        });
                });

            modelBuilder.Entity("EcoFive.Models.Models.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Governorates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "المنطقه الشرقية"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "منطقة نجران"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "منطقة مكة المكرمة"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Name = "منطقة عسير"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            Name = "منطقة حائل"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            Name = "منطقة جازان"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            Name = "منطقة الرياض"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 1,
                            Name = "منطقة القصيم"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 1,
                            Name = "منطقة المدينة المنورة"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 1,
                            Name = "منطقة الحدود الشماليه"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 1,
                            Name = "منطقة الجوف"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 1,
                            Name = "منطقة الباحه"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 1,
                            Name = "منطقة تبوك"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 2,
                            Name = "الإسكندرية"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 2,
                            Name = "الإسماعيلية"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 2,
                            Name = "أسوان"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 2,
                            Name = "أسيوط"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 2,
                            Name = "الأقصر"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 2,
                            Name = "البحر الأحمر"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 2,
                            Name = "البحيرة"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 2,
                            Name = "بني سويف"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 2,
                            Name = "بورسعيد"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 2,
                            Name = "جنوب سيناء"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 2,
                            Name = "الجيزة"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 2,
                            Name = "الدقهلية"
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 2,
                            Name = "دمياط"
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 2,
                            Name = "سوهاج"
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 2,
                            Name = "السويس"
                        },
                        new
                        {
                            Id = 29,
                            CountryId = 2,
                            Name = "الشرقية"
                        },
                        new
                        {
                            Id = 30,
                            CountryId = 2,
                            Name = "شمال سيناء"
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 2,
                            Name = "الغربية"
                        },
                        new
                        {
                            Id = 32,
                            CountryId = 2,
                            Name = "الفيوم"
                        },
                        new
                        {
                            Id = 33,
                            CountryId = 2,
                            Name = "القاهرة"
                        },
                        new
                        {
                            Id = 34,
                            CountryId = 2,
                            Name = "القليوبية"
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 2,
                            Name = "قنا"
                        },
                        new
                        {
                            Id = 36,
                            CountryId = 2,
                            Name = "كفر الشيخ"
                        },
                        new
                        {
                            Id = 37,
                            CountryId = 2,
                            Name = "مطروح"
                        },
                        new
                        {
                            Id = 38,
                            CountryId = 2,
                            Name = "المنوفية"
                        },
                        new
                        {
                            Id = 39,
                            CountryId = 2,
                            Name = "المنيا"
                        },
                        new
                        {
                            Id = 40,
                            CountryId = 2,
                            Name = "الوادي الجديد"
                        });
                });

            modelBuilder.Entity("EcoFive.Models.Models.MasterPageDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyDetails");

                    b.Property<string>("CompanyLinePhone");

                    b.Property<string>("CompanyMail");

                    b.Property<string>("CompanyPhone");

                    b.Property<string>("CompanyWorkHours");

                    b.Property<string>("FacebookAccount");

                    b.Property<string>("InstagramAccount");

                    b.Property<string>("Link1");

                    b.Property<string>("Link10");

                    b.Property<string>("Link10Title");

                    b.Property<string>("Link11");

                    b.Property<string>("Link11Title");

                    b.Property<string>("Link12");

                    b.Property<string>("Link12Title");

                    b.Property<string>("Link1Title");

                    b.Property<string>("Link2");

                    b.Property<string>("Link2Title");

                    b.Property<string>("Link3");

                    b.Property<string>("Link3Title");

                    b.Property<string>("Link4");

                    b.Property<string>("Link4Title");

                    b.Property<string>("Link5");

                    b.Property<string>("Link5Title");

                    b.Property<string>("Link6");

                    b.Property<string>("Link6Title");

                    b.Property<string>("Link7");

                    b.Property<string>("Link7Title");

                    b.Property<string>("Link8");

                    b.Property<string>("Link8Title");

                    b.Property<string>("Link9");

                    b.Property<string>("Link9Title");

                    b.Property<string>("PromoTitle");

                    b.Property<string>("PromoTitleURL");

                    b.Property<string>("TwitterAccount");

                    b.Property<string>("YoutubeAccount");

                    b.HasKey("Id");

                    b.ToTable("MasterPageDetails");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "341743f0-asd2–42de-afbf-59kmkkmk72cf6",
                            ConcurrencyStamp = "341743f0-asd2–42de-afbf-59kmkkmk72cf6",
                            Name = "SuperAdmin",
                            NormalizedName = "SuperAdmin"
                        },
                        new
                        {
                            Id = "341749f0-asu2–42de-afbf-600mkkmk72cf6",
                            ConcurrencyStamp = "341749f0-asu2–42de-afbf-600mkkmk72cf6",
                            Name = "User",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "02174cf0–9412–4cfe-afbf-59f706d72cf6",
                            RoleId = "341743f0-asd2–42de-afbf-59kmkkmk72cf6"
                        },
                        new
                        {
                            UserId = "02974cw0–9412–4nfe-afbf-59f701d72cf6",
                            RoleId = "341749f0-asu2–42de-afbf-600mkkmk72cf6"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("EcoFive.Models.Models.ApplicationUser", b =>
                {
                    b.HasOne("EcoFive.Models.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EcoFive.Models.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EcoFive.Models.Models.Governorate", "Governorate")
                        .WithMany()
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EcoFive.Models.Models.City", b =>
                {
                    b.HasOne("EcoFive.Models.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EcoFive.Models.Models.Governorate", "Governorate")
                        .WithMany()
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EcoFive.Models.Models.Governorate", b =>
                {
                    b.HasOne("EcoFive.Models.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EcoFive.Models.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EcoFive.Models.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EcoFive.Models.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EcoFive.Models.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
